### ISSUE TITLE
Run the application 

### ISSUE THREAD

**Issue by AymanKhafage** [payfort/payfort-dotnet-sdk#3]
How can run this app? Please let me know the steps for running this application.

**Comment by MohammadHananny** [comment]
This is SDK library, you can not run it by itself.
however, you can install the sample and run it as you want.
in case you have issue with integration this SDK with your system, Please let me know i will be happy to  help you on this.

**Comment by AymanKhafage** [comment]
when I call this method "string signature = PAYFORT.Security.GenerateSignature(PayfortParameters);" always the return message is "Signature mismatch." 
![image](https://user-images.githubusercontent.com/28072551/50759169-420afa00-1275-11e9-84ff-607148462ffb.png)

the attached image that has sample of my calling method.

in this method i used redirection type.

**Comment by MohammadHananny** [comment]
It seems you either  using different SHAPhase from your account settings or different SHAMethod.

Please contact "integration@payfort.com" so they can trace with you the issue and solve this.

Thanks.

**Comment by AymanKhafage** [comment]
Thanks 
![image](https://user-images.githubusercontent.com/28072551/50760444-ec385100-1278-11e9-9113-ee73dec0aea7.png)

It is working

**Comment by MohammadHananny** [comment]
Glad to help

**Comment by MohammadHananny** [comment]
Fixes #3

**Comment by mohannadsaleh** [comment]
Thank you @MohammadHananny  for your support ,
@AymanKhafage , i hope your issue is solved now and there are no other pending issues , please reopen the issue if you still facing another issues or you have points you want to discuss .

Best Regards,
Mohannad
